### ISSUE TITLE
"Could not resolve reference to" en el empaquetado de linux

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#1]
Probado en Huayra (Debian based).
Es independiente de si lo corro en la carpeta actual o en otra.

![Selection_028](https://user-images.githubusercontent.com/5421992/166634858-5c2d2336-e376-44a9-8023-90be63ce2bef.png)

```
✗ Uh-oh... An error occurred during the run!
  Error: Could not resolve reference to /home/alf/repos/pdep/2021/2021-o-recufeb/
    at Environment.getNodeByFQN (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/model.js:654:19)
    at Environment.<anonymous> (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/decorators.js:19:39)
    at Interpreter.run (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/interpreter.js:17:54)
    at Command.default_1 (/snapshot/wollok-ts-cli/dist/commands/run.js:25:72)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.parseAsync (/snapshot/wollok-ts-cli/node_modules/commander/lib/command.js:916:5)
```

**Comment by asanzo** [comment]
Borré node modules, volví a compilar, y ahora parece andar por alguna razón (con el mismo problema #3 ) 

![image](https://user-images.githubusercontent.com/5421992/166642941-2257006e-dc47-4dba-8efc-c34768fde156.png)

Así que doy por cerrado este issue, porque no sé qué demonios pasó.
