### ISSUE TITLE
Correr en Windows con consola `cmd` hace que no se reconozcan los tests

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok-ts-cli#109]
Teniendo este código:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/10454118/55b8d9b5-d980-4c65-b025-2aa17927024f)

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/10454118/e48ce6d3-7035-4431-8e2a-c71cd906028e)
Con version 0.1.0, al hacer click en cualquiera de los botones/links para correr los tests y teniendo configurada la consola por defecto `cmd`, no se reconocen los tests. La versión 0.1.1 directamente no muestra los links para ejecutar, así que no es una opción para corregir este problema. En la versión 0.1.0 se ve este resultado:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/10454118/cda03561-3d33-4994-9624-e88d70362532)

Si cambio la consola por defecto a PowerShell, funciona correctamente:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/10454118/743c9813-5147-48f2-a889-200c1fc4f704)

Versión de VSC:
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

Output al correr los tests:
```
node:internal/modules/cjs/loader:1132
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js:3:46)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\matia\\.vscode\\extensions\\uqbar.wollok-lsp-ide-0.1.1\\server\\out\\server.js'
  ]
}

Node.js v18.15.0
[Info  - 6:06:57 PM] Connection to server got closed. Server will restart.
[Error - 6:06:57 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:06:57 PM] Wollok client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1132
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js:3:46)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\matia\\.vscode\\extensions\\uqbar.wollok-lsp-ide-0.1.1\\server\\out\\server.js'
  ]
}

Node.js v18.15.0
[Info  - 6:06:58 PM] Connection to server got closed. Server will restart.
[Error - 6:06:58 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:06:58 PM] Wollok client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1132
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js:3:46)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\matia\\.vscode\\extensions\\uqbar.wollok-lsp-ide-0.1.1\\server\\out\\server.js'
  ]
}

Node.js v18.15.0
[Info  - 6:06:59 PM] Connection to server got closed. Server will restart.
[Error - 6:06:59 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:06:59 PM] Wollok client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:06:59 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1132
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js:3:46)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\matia\\.vscode\\extensions\\uqbar.wollok-lsp-ide-0.1.1\\server\\out\\server.js'
  ]
}

Node.js v18.15.0
[Info  - 6:06:59 PM] Connection to server got closed. Server will restart.
[Error - 6:06:59 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:06:59 PM] Wollok client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:06:59 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1132
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (c:\Users\matia\.vscode\extensions\uqbar.wollok-lsp-ide-0.1.1\server\out\server.js:3:46)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\matia\\.vscode\\extensions\\uqbar.wollok-lsp-ide-0.1.1\\server\\out\\server.js'
  ]
}

Node.js v18.15.0
[Error - 6:07:00 PM] The Wollok server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 6:07:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:07:00 PM] Wollok client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:07:00 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

Probablemente pasa siempre, pero por las dudas paso transcripción del código:
`example.wlk`
```Wollok
object pepita {
    var property energia = 0

    method volar() { energia -= 2 }
    method comer() { energia += 5 }
}
```

`tests.wtest`
```Wollok
import example.*

describe "This is a test group" {
    test "This is an individual test" {
        assert.that(pepita.energia() == 0)
    }
}
```

**Comment by fdodino** [comment]
En la épica #115 ya se modificó para trabajar con parámetros específicos, hay que ver si lo actualizamos en Wollok LSP IDE para que funcione o si hay algo que tunear desde el cli.

**Comment by fdodino** [comment]
Ahí lo probé en Windows con el PR de Wollok LSP IDE:

## Git Bash
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/50de4b14-0d57-473b-8540-b6734f1ad6d8)

## Powershell

Vean el ´pwsh - Task´ en el panel de la Terminal:

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/b1e832db-d8d7-46b1-b85d-0f1dc4a293e5)

## Cmd

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/bb3e8dd7-83e5-4fbd-b90a-98f99f2af682)

Qué lindo que es trabajar en Windows, eh?! Muy edificante!

Todo esto fue cambiando [la terminal por defecto](https://stackoverflow.com/questions/44435697/change-the-default-terminal-in-visual-studio-code).
