### ISSUE TITLE
error al correr juego de repo 

### ISSUE THREAD

**Issue by hernanconiglio** [uqbar-project/wollok-ts-cli#61]
repo publico: https://github.com/hernanconiglio/pacmanBasicGame

Error que arroja:
```
 *  Executing task: /home/hernan/wollok-dev/wollok-ts-cli-linux run 'program.pacman' --skipValidations -p /home/hernan/Objetos1/pacmanBasicGame/src 

Running program.pacman on /home/hernan/Objetos1/pacmanBasicGame/src
Running program.pacman...

✗ Uh-oh... An error occurred during the run!
  wollok.lang.EvaluationError wrapping TypeScript Error: Could not resolve reference to pacman or its a reference to void
    at program.pacman [program.wpgm:4]
    at root [--:--]
    Derived from TypeScript stack
    at Evaluation.exec (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:283:39)
    at exec.next (<anonymous>)
    at Evaluation.execSend (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:395:37)
    at execSend.next (<anonymous>)
    at Evaluation.exec (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:268:49)
    at exec.next (<anonymous>)
    at Evaluation.execBody (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:330:34)
    at execBody.next (<anonymous>)
    at Evaluation.exec (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:256:49)
    at exec.next (<anonymous>)
✓ Game available at: http://localhost:3000
✓ Running game!
```

**Comment by PalumboN** [comment]
Related to https://github.com/uqbar-project/wollok-ts/issues/96

**Comment by PalumboN** [comment]
Este juego anda con los cambios en https://github.com/uqbar-project/wollok-ts-cli/pull/85 y poniendole otro nombre al program para que no colisione con el object (más detalles en https://github.com/uqbar-project/wollok-language/issues/122)
